### ISSUE TITLE
Not able to start the project in dev

### ISSUE THREAD

**Issue by CuriosBasant** [vercel/next-rsc-demo#19]
I've cloned this repo demo, and tried to run it with `yarn dev`, but it is not working and giving the following error.
![image](https://user-images.githubusercontent.com/49369883/147966885-46529226-faca-4954-8a62-2306b38cd0b0.png)

**Comment by f-o-w-l** [comment]
I also experienced this issue and solved it by switching node to the LTS version. Shout out to the [asdf library](https://github.com/asdf-vm/asdf) which allows switching between different node package versions globally and by directory as easily as `asdf local nodejs lts`.

**Comment by CuriosBasant** [comment]
> I also experienced this issue and solved it by switching node to the LTS version. Shout out to the [asdf library](https://github.com/asdf-vm/asdf) which allows switching between different node package versions globally and by directory as easily as `asdf local nodejs lts`.

Hey I do have node v17.2.0 installed, isn't that enough?

**Comment by f-o-w-l** [comment]
> > I also experienced this issue and solved it by switching node to the LTS version. Shout out to the [asdf library](https://github.com/asdf-vm/asdf) which allows switching between different node package versions globally and by directory as easily as `asdf local nodejs lts`.
> 
> Hey thanks, but I do have node v17.2.0 installed, isn't that enough?

The LTS version stands for "long-term support". [In nodejs's case](https://nodejs.org/en/about/releases/) this "guarantees that critical bugs will be fixed for a total of 30 months," other libraries might define it slightly differently. Right now the LTS node version is 16.13.1.

**Comment by CuriosBasant** [comment]
Thanks, installing lts for node, did solved the issue.
