### ISSUE TITLE
Non-page server component cannot import client component

### ISSUE THREAD

**Issue by zaiste** [vercel/next-rsc-demo#7]
It seems that client components can be only directly imported from a page component. 

For example, the `News` component located in `rsc.server.js` can import the `Story` client component just fine. If we, however, move the `StoryWithData` to a separate file (with the `.server` suffix or none i.e. a shared component), Next.js returns errors.

Here's a diff off a branch from my fork that shows this issue: 
https://github.com/vercel/next-rsc-demo/compare/main...zaiste:non-page-server-comp-cannot-import-client-comp

**Comment by shuding** [comment]
Thanks for reporting! I can reproduce this bug and we're working on a fix.

**Comment by zaiste** [comment]
@shuding thanks for a speedy fix. You rock!

**Comment by shuding** [comment]
Should be fixed in latest `next@canary` 🎉
