### ISSUE TITLE
How to rerender RSC?

### ISSUE THREAD

**Issue by Regaron** [vercel/next-rsc-demo#8]
How can we rerender(refetch) RSC to show updated data?

**Comment by huozhi** [comment]
@Regaron We have undocumented API now in latest version of next.js could let you do that. Docs update will come soon.

Example
```js
import { unstable_useRefreshRoot } from 'next/rsc'

export deafult function Page() {
   cons refresh = unstable_useRefreshRoot()
   // ...
   return <Content><button onClick={refresh}>update</button></Content>
}
```

Would love to hear the feedback from you
